### ISSUE TITLE
Different "CANAPE“ analysis results between R package "canaper" and "biodiverse"

### ISSUE THREAD

**Issue by chenwy66** [joelnitta/canaper#34]
Hi,  when I used R package "canaper", I met some problem, please help me, thank you very much!

 
I used both R package "canaper" and "Biodiverse" to do "CANAPE" analysis, but I found different results. Both of them I set the iterations = 100000. 

The "canaper" code I use is:

  "acacia_rand_res <- cpr_rand_test(
  comm, phy,
  null_model = "curveball",
  n_reps = 10000, n_iterations = 100000,
  tbl_out = TRUE)
acacia_canape <- cpr_classify_endem(acacia_rand_res)"

The randomisation in "Biodiverse" I set as:
![image](https://github.com/user-attachments/assets/23b29e62-2f68-47a4-b2f2-3e5e1167b67d)

The result of "canaper" is:
<img width="251" alt="1723711371975" src="https://github.com/user-attachments/assets/96a7c21d-b40a-4adc-91bc-6f10b8874ee7">

The result of "biodiverse" is:
<img width="247" alt="1723711268338" src="https://github.com/user-attachments/assets/9dd61dd7-1bba-46e5-afd6-a19d24cbbde8">

The purple grids mean paleo endemism, red grids mean neo endemism, green grids mean mixed endemism, and the blue grid means super endemism. 

This two results are very similar, but still have some different.Why did this happen? Which result is more credible? Or is there anything wrong with my code or settings?

**Comment by joelnitta** [comment]
There is nothing wrong with your code or settings, as far as I can tell.

Since CANAPE is based on randomizations, it is highly unlikely to obtain exactly the same results (as long as you use a different random seed), even from running the same code twice in canaper or Biodiverse. Of course, we can "hone in" on similar results by increasing the number of random replicates.

In the [canaper paper](https://nsojournals.onlinelibrary.wiley.com/doi/full/10.1111/ecog.06638), we used 999 replicates and obtained 98.4% similar results between canaper and Biodiverse. I cannot tell just from those screenshots how similar the results are (in percentage). Could you calculate that and let me know?

Also, another factor contributing to the difference in results between Biodiverse and canaper is that they use different randomization algorithms. But, the development version of Biodiverse [now supports the `curveball` algorithm](https://github.com/shawnlaffan/biodiverse/pull/915), which is also available in canaper. So I recommend you try the development version of Biodiverse with `curveball` and see if that helps.

**Comment by chenwy66** [comment]
The results' similarity between canaper and Biodiverse is 97.7%.  

Thank you very much for your patient response and suggestions. I download the Biodiverse version 4.99, but I didn't found the curveball algorithm bottom from Randomisation settings. 
<img width="749" alt="image" src="https://github.com/user-attachments/assets/e148c816-2160-46f6-93ca-831954bf03cd">

I checked the update log for version 4.9,  it doesn't mention the addition of the "curveball algorithm." However, the log for version 5.0 states that this algorithm will be supplemented. Whether this algorithm is not be fully developed in the current 4.9 development version?

**Comment by joelnitta** [comment]
I don't think curveball is included in Biodiverse 4.9, since the [PR implementing curveball](https://github.com/shawnlaffan/biodiverse/pull/915) was merged Feb. 6 2024, but [4.9](https://github.com/shawnlaffan/biodiverse/releases/tag/r4.99_002) was released Feb. 3 2024.

@shawnlaffan can you confirm?

**Comment by shawnlaffan** [comment]
The next development version of Biodiverse (4.99_003) will include curveball.  It should be out sooner rather than later.  

However, the choice of algorithm should not make much difference to the results.  All that matters is that the algorithm generate random realisations of the taxon distributions.

Also, ```iterations to run``` in Biodiverse is equivalent to ```n_reps``` for canaper.  So there were 100,000 iterations in Biodiverse but 10,000 in canaper.  This should not make much difference, though, as the results will not change much after 10,000 iterations unless the data set is very large and thus needs more iterations to achieve convergence.  

What is more important is the data you are analysing.  How many cells and taxa are there?  How close to the significance thresholds are the cells in the images?  Isolated cells are also often due to sampling differences, and these could include errors.

**Comment by joelnitta** [comment]
Thanks @shawnlaffan for the prompt response and catching the difference in the OP in settings that I missed.

I think @chenwy66 is only using it on the demo dataset (Australian Acacia) for now.

**Comment by shawnlaffan** [comment]
Thanks Joel.  @chenwy66 - please check the underlying significance scores for the cells that differ.  My expectation is that they will be close to 0.95, 0.975 or 0.025 depending on which index one looks at (0.95 for the PE scores given they are one-tailed tests, and other two for RPE given it is two-tailed).

**Comment by chenwy66** [comment]
Sorry for my late reply and thank you both for your patience. The data I used contained 6413 distribution records for 223 species, with 431 grids. I re-ran the R package "canaper" and "biodiverse", set the "iterations to run" and the "n_reps" to 10,000, and set the same random seed. This time I obtained 98.6% similar results between "canaper" and "biodiverse". There are six grids with different results. Five grids were identified as mixed endemism in "biodiverse"(RPE significance were close to 0.95) , while in the "canaper" package were identified as not significant; one grid was identified as neo endemism in "biodiverse"(RPE significance was close to 0.01), while in the "canaper" package was identified as mixed endemism.

different grids' significance of "canaper"
<img width="323" alt="6eda894a136a626fe4e865b85ef5746" src="https://github.com/user-attachments/assets/f5a67063-a100-44ca-ac61-fcef3cfb68d7">

**Comment by shawnlaffan** [comment]
Six cells different from 431 is not much difference.  I suspect you'd get similar differences between sequential runs using only Biodiverse or canaper.  

One minor point - a grid is a collection of cells.

**Comment by chenwy66** [comment]
Thank you very much!

**Comment by joelnitta** [comment]
@chenwy66 it seems your questions have been answered, so I will close this. Please let me know if you have any more questions!
